version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ~/.kube:/root/.kube
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "kubernetes.docker.internal:host-gateway"
    environment:
      - KUBERNETES_TRUST_CERTIFICATES=true
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge