apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: managedredis.redis.managed.com
spec:
  group: redis.managed.com
  names:
    kind: ManagedRedis
    listKind: ManagedRedisList
    plural: managedredis
    singular: managedredis
    shortNames:
      - mredis
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - version
                - replicas
              properties:
                version:
                  type: string
                  description: "Redis version to deploy"
                  pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
                replicas:
                  type: integer
                  description: "Number of Redis instances (1 for standalone, >1 for Primary-Replica)"
                  minimum: 1
                  maximum: 5
                resources:
                  type: object
                  properties:
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                          pattern: "^[0-9]+m?$"
                        memory:
                          type: string
                          pattern: "^[0-9]+Mi$|^[0-9]+Gi$"
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                          pattern: "^[0-9]+m?$"
                        memory:
                          type: string
                          pattern: "^[0-9]+Mi$|^[0-9]+Gi$"
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: "Current phase of the Redis cluster"
                  enum:
                    - Pending
                    - Creating
                    - Running
                    - Failed
                primaryEndpoint:
                  type: string
                  description: "Endpoint for primary Redis instance"
                readerEndpoint:
                  type: string
                  description: "Endpoint for replica Redis instances"
                nodes:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      role:
                        type: string
                        enum:
                          - Primary
                          - Replica
                      status:
                        type: string
                        enum:
                          - Ready
                          - NotReady
                      endpoint:
                        type: string
      additionalPrinterColumns:
        - name: Version
          type: string
          description: Redis Version
          jsonPath: .spec.version
        - name: Replicas
          type: integer
          description: Number of Redis instances
          jsonPath: .spec.replicas
        - name: Phase
          type: string
          description: Current Phase
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp 